config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "users#index"
  # Define endpoints for
  post "/api/register", to: 'authentication#register'
  post '/api/login', to: 'authentication#login'
  get '/api/users/:user_id/posts', to: 'posts#posts'
  get '/api/posts/:id/comments', to: 'comments#comments'
  get '/api/users/:user_id/posts/:id/comments', to: 'all#comments'
  post '/api/users/:user_id/posts/:id/comments', to: 'comments#add_comment'

  resources :users, only: [:index, :show] do
resources :posts, only: [:index, :show, :new, :create, :destroy] do      
  resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create]
  end
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_writer :login

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  validates :name, presence: true
  validates_format_of :name, with: /^[a-zA-Z0-9_.]*$/, multiline: true

  def recent_posts
    posts.order('created_at DESC').limit(3)
  end

  def login
    @login || name || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(['name = :value OR email = :value', { value: login }]).first
    elsif conditions.key?(:name) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end

  def admin?
    role == 'admin'
  end

  def authenticate(password)
    valid_password?(password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_request
  def index
    @users = all_users
  end

  def show
    @user = User.includes(:posts).find(params[:id])
  end
end

app/controllers/users_controllers.rb
class UsersController < ApplicationController
    def index; end
  
    def show; end
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_bio.hmtl.erb
<section id="bio">
	<h3>My Bio</h3>
	<p><%=bio%></p>
</section>

app/views/users/_bio.html.erb
<section id="bio">
	<h3>My Bio</h3>
	<p><%=bio%></p>
</section>

app/views/users/_user.hmtl.erb
<section class="user">
  <img class="image" src="<%=user.photo%>" alt="user-image" />
  <%= link_to user_path(user) do%>
  <div class="card">
     <h2><%= user.name%> </h2>
     <p> Number of posts: <%= user.posts_counter%></p>
  </div class="card">
  <%end%>
</section>

app/views/users/_user.html.erb
<section class="user">
  <img class="image" src="<%=user.photo%>" alt="user-image" />
  <%= link_to user_path(user) do%>
  <div class="card">
     <h2><%= user.name%> </h2>
     <p> Number of posts: <%= user.posts_counter%></p>
  </div class="card">
  <%end%>
</section>

app/views/users/_user_information.hmtl.erb
<%= link_to user_post_path(@user,id:post.id) do%>
<section class="user-info">
<h4><%=post.title%></h4>
 <p><%=post.text%></p>
 <small>
    My Comments: <%=post.comments_counter%>, Likes: <%=post.likes_counter%>       
</small>
</section>
<%end%>	

app/views/users/_user_information.html.erb
<%= link_to user_post_path(@user,id:post.id) do%>
<section class="user-info">
<h4><%=post.title%></h4>
 <p><%=post.text%></p>
 <small>
    My Comments: <%=post.comments_counter%>, Likes: <%=post.likes_counter%>       
</small>
</section>
<%end%>	

app/views/users/index.html.erb
<%= stylesheet_link_tag "users" %>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>My users</title>
</head>
<body>
    <main id ="container">  
    <%= render @users %>
    </main>
</body>
</html>

app/views/users/show.html.erb
<%= stylesheet_link_tag "user_info" %>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>My specific user</title>
</head>
<body>
<main id ="container"> 
  <%= render @user%>
  <%= render partial: "bio" , locals:{bio:@user.bio}%>
  <%= render partial: "user_information", as: "post" , collection: @user.recent_posts%>
  <button id="show-posts"><%= link_to "See all posts", user_posts_path(@user) %></button>
  </main>
</body>
</html>