config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "users#index"
  # Define endpoints for
  post "/api/register", to: 'authentication#register'
  post '/api/login', to: 'authentication#login'
  get '/api/users/:user_id/posts', to: 'posts#posts'
  get '/api/posts/:id/comments', to: 'comments#comments'
  get '/api/users/:user_id/posts/:id/comments', to: 'all#comments'
  post '/api/users/:user_id/posts/:id/comments', to: 'comments#add_comment'

  resources :users, only: [:index, :show] do
resources :posts, only: [:index, :show, :new, :create, :destroy] do      
  resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create]
  end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments
  has_many :likes
  after_save :update_post_counter

  validates :title, presence: true, length: { minimum: 4, maximum: 250 }
  validates :comments_counter, presence: true,
                               numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true,
                            numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  def update_post_counter
    author.increment!(:posts_counter)
  end

  def recents_comments
    comments.includes(:author).order('created_at desc').limit(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_request
  def index
    @user = User.find(params[:user_id])
  end

  def show
    @user = User.where(id: params[:user_id])[0]
    @post = @user.posts.where(id: params[:id])[0]
    @posts = Post.where(author_id: params[:user_id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.update_posts_counter
    respond_to do |format|
      if @post.save
        flash[:notice] = 'Post created succesfully'
        format.html { redirect_to "#{users_path}/#{current_user.id}" }
      else
        flash[:notice] = 'Failed creation a post. Try again'
        format.html { render :new }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @author = @post.author
    @author.posts_counter -= 1
    @post.destroy!
    redirect_to user_posts_path(id: @author.id), notice: 'Post was deleted successfully!'
  end

  def posts
    user = User.find(params[:user_id])

    respond_to do |format|
      format.json { render json: user.posts }
    end
  end

  private

  def post_params
    params.require(:post).permit(:author_id, :title, :text, :comments_counter, :likes_counter)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments.html.erb
<p>
<span class="comment"><%=comment.author.name%>:</span> 
<span class="comment"><%=comment.text%></span>
</p>

app/views/posts/_post.html.erb
<%=link_to user_post_path(id:post.id) do%>
<section class="user-info">
<h4><%=post.title%></h4>
 <p>
   <%= 
     post.text.length > 100 && post.text + "..."
     post.text unless post.text.length > 100 
   %>   
</p>
 <small>
    Comments: <%=post.comments_counter%>, Likes: <%=post.likes_counter%>       
</small> 
<%=render partial:'likes/like', locals:{like:@like,post_id:post.id,distination:params[:action]}%>
</section>
<%end%>

app/views/posts/_post_information.html.erb
<section class="user-info">
<h4><%=post.title%> by <%=post.author.name%></h4>
 <p><%=post.text%></p>
 <small>
    Comments: <%=post.comments_counter%>, Likes: <%=post.likes_counter%>       
</small> 
<%=link_to new_user_post_comment_path(post_id:post.id) do%>
   <button class="create-comment">Create comment</button>
  <%end%> 
<%=render partial:'likes/like', locals:{like:@like,post_id:post.id,distination:params[:action]}%> 
</section>
<%if post.comments.length > 0 %>
<section class="comment-section">
<%= render partial:'comments', as: 'comment', collection:comments%>
</section>  
<%end%>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>See user's posts</title>
</head>
<body>
  <main id ="container"> 
  <%= render partial:'users/user', locals:{user: @user} %>
   <%=link_to new_user_post_path do%>
   <button class="create-post">Create post</button>
  <%end%>
   <% @posts.each do |post| %>
  <%= render post%>
  <%if post.comments.length > 0 %>
   <section class="comment-section">
    <%= render partial:'comments', as: 'comment', collection:post.recents_comments%>
   </section>
   <%end%>
   <%end%>
  <button id="show-posts">My pagination</button>
</main>     
</body>
</html>

app/views/posts/new.html.erb
<%=form_with model: [:user, post], method: :post, id: 'form' do |form| %>
  <%=label(:post,:Title)%> 
  <%=form.text_field :title%>
  <%=label(:post,:Topic)%> 
  <%=form.text_area :text%>
  <%=form.submit "Save" %>
<% end %>

app/views/posts/show.html.erb
<section class="posts-section">
  <% if @user %>
    <% if @post %>
      <div class="bordered-box">
        <div>
          <h2><%= @post.title %> by <%= @post.author.name %></h2>
          <div class="post-info">Comments: <%= @post.comments.length %>, Likes: <%= @post.likes.length %></div>
          <%= render partial: "posts/like", locals: { url: "/users/#{@user.id}/posts/#{@post.id}/like", post: @post } %>
           <% if can? :destroy, @post %>
    <%= button_to "Delete post", user_post_path(user_id: @post.author.id, post_id: @post.id), method: :delete, class: 'mb-10 hover:opacity-60'  %>
  <% end %>
        </div>
        <p>
        <%= @post.text %>
        </p>
      </div>
      <%= render partial: "posts/add_comment" %>
      <% if @post.comments.length != 0 %>
        <ul class="bordered-box">
          <% @post.recent_comments.each do |comment| %>
            <li>
            <span><%= comment.author.name %> : </span>
            <span> <%= comment.text %> </span>
            </li>
          <% end %>
        </ul>
      <% else %>
        <h2>No comments added </h2>
      <% end %>
      
    <% else %>
      <h2>Not founded</h2>
    <% end %>
  <% else %>
    <h1>Not founded</h1>
  <% end %>
</section>  